name: Test - Release and Publish
on:
   pull_request:
   push:
      branches: main
      tags: ["!**"]
   #  workflow_run:
   #     workflows: [Lint and Type]
   #     branches: main
   #     types: completed

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
   test-release:
      runs-on: ubuntu-latest
      timeout-minutes: 15
      strategy:
         matrix:
            node-version: [lts/*]

      steps:
         - name: Checkout repo
           uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

         - name: Setup pnpm
           uses: pnpm/action-setup@v4
           with:
              version: 9.12.0

         - name: Setup Node.js
           uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
           with:
              node-version: ${{ matrix.node-version }}
              cache: "pnpm"

         - name: Install dependencies and build
           run: |
              pnpm install --frozen-lockfile
              pnpm build

         - name: Deploy and test release via pkg.pr.new
           run: pnpm test:release

   #  on--workflow-failure:
   #     runs-on: ubuntu-latest
   #     timeout-minutes: 15

   #     if: ${{ github.event.workflow_run.conclusion == 'failure' }}
   #     steps:
   #        - run: |
   #             echo "Triggering Workflow: ${{ github.event_name }} failed woefully"
   #             echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
   #             echo "Workflow run status: ${{ github.event.workflow_run.status }}"
